# NumPy Library
- Numerical Python 약자(numpy)
- Python에서 수치계산을 위한 핵심 라이브러리
- 'ndarray'(N-dimensional array) 클래스 지원

In [3]:
# import : 외부라이브러리 불러오기
# alias(as) : 별칭 부여
import numpy as np

## ndarray(N-dimensional array)
- 1. 다양한 수학함수 지원
- 2. 빠른 연산속도
- 3. 브로드캐스팅(차원을 동일시 하는 기능)
- 4. 다차원의 배열지원(보통은 2차원까지 사용)

- '동일한 자료형'을 가지는 값들이 '배열'형태로 존재함
- 각 값들은 순서가 있다. -> index가 부여되어 있다

### 1.ndarray 생성하기
- np.array(리스트 or 튜플)

In [4]:
# ndarray 생성하기 >> 1차원 (1)
# 리스트 데이터를 array화로 형변환 하는 방법

#list 생성
list1 = [1,2,3,4,5]

# array 생성
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
# ndarray 생성하기 >> 1차원 (2)
# 직접 array화로 생성
arr2 = np.array([2,3,4,5,6])
arr2

array([2, 3, 4, 5, 6])

In [7]:
# ndarray 생성하기 >> 2차원
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# 2차원 형태의 리스트 >> ndarray와 차이가 있음
# list는 차원수를 인식하지 못 함
# ndarray는 차원수를 인식한다
list2 = [[1,2,3],[4,5,6],[7,8,9]]
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### 2.ndarray 확인하기 >> "속성" 이나 "키워드"

In [10]:
# array 차원 수 확인하기
# array명.ndim

print(arr1.ndim)
print(arr3.ndim)

1
2


In [11]:
# array 모양(크기) 확인하기
# array명.shape
# (행, 열)

print(arr1.shape) #1차원은 열의자리 생략
print(arr3.shape)

(5,)
(3, 3)


In [13]:
# array의 전체요소개수 확인하기
# array명.size

print(arr1.size)
print(len(arr1))
print(arr3.size)
print(len(arr3))

5
5
9
3


In [15]:
def array_info(array) :
    print(array)
    print("ndim(차원수):", array.ndim)
    print("shape(모양):", array.shape)
    print("dtype(데이터타입):", array.dtype)
    print("size(요소 전체 갯수):", array.size)

In [16]:
array_info(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim(차원수): 2
shape(모양): (3, 3)
dtype(데이터타입): int32
size(요소 전체 갯수): 9


### 2-1 array dtype 및 shape 변경

In [17]:
# 데이터 타입 변경하기 1
list3 = [[1.7,4.2,3.6],[4.1,2.9,5.8]]
temp1 = np.array(list3)
temp2 = np.array(list3, dtype = np.int64)

array_info(temp1)
print()
array_info(temp2)

[[1.7 4.2 3.6]
 [4.1 2.9 5.8]]
ndim(차원수): 2
shape(모양): (2, 3)
dtype(데이터타입): float64
size(요소 전체 갯수): 6

[[1 4 3]
 [4 2 5]]
ndim(차원수): 2
shape(모양): (2, 3)
dtype(데이터타입): int64
size(요소 전체 갯수): 6


In [18]:
# 데이터 타입 변경하기 2
# .astype(np.데이터타입)
# 버린 값을 다시 불러오기 XX

temp2 = temp2.astype(np.float64)
array_info(temp2)

[[1. 4. 3.]
 [4. 2. 5.]]
ndim(차원수): 2
shape(모양): (2, 3)
dtype(데이터타입): float64
size(요소 전체 갯수): 6


In [21]:
# ndarray 특정 크기 변환
# 2차원의 경우 행과 열의 값이 맞게 떨어져야 함
# array명.reshape(행, 열)

temp2 = temp2.reshape(3,2)
array_info(temp2)

[[1. 4.]
 [3. 4.]
 [2. 5.]]
ndim(차원수): 2
shape(모양): (3, 2)
dtype(데이터타입): float64
size(요소 전체 갯수): 6


### 3. 특정한 값으로 ndarray 생성하기
- np.zeros((행,열))  #튜플값
- np.ones((행,열))
- np.full((행,열), 값 )
- np.arange(시작값, 끝값, 증감량)
- np.random.rand(행,열)
- np.random.randint(시작값, 끝값, size=(행,열))

In [22]:
# np.zeros((행,열)) : 모든 값을 0으로 초기화해서 선언
# 기본 데이터형 : float

arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# np.ones((행,열)) : 모든 값을 1로 초기화
# 기본 데이터형 : float

arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
# np.full((행,열), 값 ) : 원하는 값으로 초기화
# 기본데이터형 : 입력값

arr_full = np.full((3,4), 10)
arr_full

#dtype='<U2  문자열 <U(문자길이)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [46]:
# np.random.randint(시작값, 끝값, size=(행,열)) (size 생략시 1차원배열 생성)
# 랜덤값으로 배열 생성(int)
# 끝값 포함 X

arr_randint = np.random.randint(1,10,size=(3,2))
arr_randint

array([[1, 7],
       [7, 4],
       [8, 8]])

In [50]:
# 실습
# 1부터 50이 담긴 1차원 array 생성(array 형변환으로 생성)
# list 사용해서 생성

#list4 = []
#for i in range(1,51) :
#    list4.append(i)

#위의 내용 한줄로 작성시
list4 = [i for i in range(1,51)]

arr4 = np.array(list4)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [51]:
# np.arange(시작값,끝값)
# range() 함수처럼 범위 지정(끝값 포함X)
# numpy에서 제공하는 함수

arr2 = np.arange(1,51)
array_info(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
ndim(차원수): 1
shape(모양): (50,)
dtype(데이터타입): int32
size(요소 전체 갯수): 50


### 4.array 연산(요소별 연산)
- '요소별 연산'에 특화되어 있다
- 브로드캐스팅 : 차원수를 자동으로 맞춰준다

In [53]:
# list의 연산방식 // array의 연산과 차이점을 확인하기
list1 = [1,2,3]
list2 = [4,5,6]

#list + list
print(list1+list2)

# list 요소별 연산 >> 각각 값을 도출(인덱싱)해야 연산이 가능
print(list1[0]+list2[0])

[1, 2, 3, 4, 5, 6]
5


In [54]:
# np.array()의 연산

arr_a = np.array(list1)
arr_b = np.array(list2)

# np.array + np.array
print(arr_a+arr_b)

[5 7 9]


In [55]:
arr2_a = np.array([[1,2,3],[4,5,6]])
arr2_b = np.array([[7,8,9],[10,11,12]])

print(arr2_a + arr2_b)

[[ 8 10 12]
 [14 16 18]]


In [56]:
# 자동으로 인덱싱을 하여 요소들을 찾아가 연산을 수행한다
arr2_a+3

array([[4, 5, 6],
       [7, 8, 9]])

### 5.array 인덱싱 & 슬라이싱
- 인덱싱(Indexing) : 요소하나를 가리키는 것
- 슬라이싱(Slicing) : 요소들을 잘라오는 것
- 리스트 or 튜플 형과 같이 인덱싱, 슬라이싱 방법은 동일함

In [57]:
# 1차원 array 생성
arr_1 = np.arange(0,10)
print(arr_1)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
# 인덱싱
print(arr_1[4])

# 슬라이싱
print(arr_1[2:5])

4
[2 3 4]


In [61]:
# 슬라이싱을 하고 한번에 데이터 넣기

# 리스트는 슬라이싱하고 값을 수정하게 되면 범위 자체가 하나의 요소로 반환
list1 = [0,1,2,3,4,5,6,7,8,9]
list1[3:] = [10]
print(list1)

# array는 슬라이싱 된 요소들의 자리에 각각 하나씩 값을 넣는다
arr_1[3:] = 10
print(arr_1)

[0, 1, 2, 10]
[ 0  1  2 10 10 10 10 10 10 10]


#### 5-1 2차원 array 인덱싱& 슬라이싱
- 인덱싱 : [행값, 열값]
- 슬라이싱 : [행의 시작값:행의 끝값 , 열의 시작값:열의 끝값]

In [62]:
arr2 = np.arange(1,51).reshape(5,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [64]:
# 인덱싱 : [행값, 열값]
# 튜플 인덱싱
arr2[1,2]

13

In [65]:
# 인덱싱 : [행값, 열값]
# 두 번 연산 진행(일반 인덱싱)
arr2[1][2]

13

In [68]:
# 2차원 array 슬라이싱
# array[행 시작값: 행 끝값,{ 열 시작값 : 열 끝값 }]  {} >> 생략가능
# 시작값이나 끝값을 생략시 일반인덱싱으로 정상적인 출력 불가능
arr2[2:,:9]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr2[:,0]

array([ 1, 11, 21, 31, 41])

In [71]:
arr2[:4,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])